/*
 * Copyright (c) 2025 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 18.10.2025 23:31:03

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1520;
#else
constexpr int kTensorArenaSize = 496;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,148 } };
const TfArray<1, float> quant0_scale = { 1, { 7.8029942512512207, } };
const TfArray<1, int> quant0_zero = { 1, { -127 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data1[2] = { -13, 13, };
const TfArray<1, int> tensor_dimension1 = { 1, { 2 } };
const TfArray<1, float> quant1_scale = { 1, { 0.0015749975573271513, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data2[2*10] = { 
  73, -106, 73, 112, 127, -89, -45, -110, 11, 93, 
  76, 15, -22, -25, -99, 6, -123, 56, -99, 37, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 2,10 } };
const TfArray<1, float> quant2_scale = { 1, { 0.0053740767762064934, } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[10] = { -3, 0, -2, 1, -2, 3, -2, 2, 0, -2, };
const TfArray<1, int> tensor_dimension3 = { 1, { 10 } };
const TfArray<1, float> quant3_scale = { 1, { 0.0070191030390560627, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[10*20] = { 
  21, -127, -42, 3, 56, 8, 64, -73, -5, -34, 13, 10, 39, 68, 29, -51, 0, -17, -45, 16, 
  -35, -71, 42, 42, 33, -25, -32, -60, -58, 11, -33, -33, 39, 14, 43, 56, -31, 21, -27, -19, 
  -15, -60, -2, 63, -32, -37, -24, 11, -25, -7, 18, 31, -13, -55, -9, -43, 52, -60, -62, -50, 
  37, 5, 58, 2, -41, 48, -35, -28, -17, 46, 62, 31, -45, -68, -2, -28, -16, -33, 66, 53, 
  -30, 14, -60, -29, -55, 42, -24, 14, -57, 37, 55, 34, -12, 29, 14, -59, -30, 61, 44, 34, 
  -52, 61, -43, 36, -14, -71, 0, 53, -72, -27, 50, 38, -32, 42, -13, -42, -23, 40, -41, 4, 
  57, 26, -37, -50, 48, 47, 7, -21, -16, 2, 37, 26, -44, -27, 6, -11, 37, -12, -11, -21, 
  -10, 105, 29, 60, 34, 54, 53, -69, 70, -20, -35, 69, 41, 6, -63, 31, 53, 3, 8, 51, 
  39, 25, 34, 25, 54, 21, -68, -16, -18, 8, 59, 13, -3, -65, -21, 59, -54, 44, -29, -20, 
  28, -48, -10, -4, 47, 61, -12, 6, 49, -57, -39, 31, -46, -36, 35, -12, -11, 54, 0, 49, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 10,20 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0061747068539261818, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[20] = { -1, 2, 0, 1, 1, -1, 1, 1, -1, -1, -1, -1, 0, 0, -1, 0, 0, 0, -1, -2, };
const TfArray<1, int> tensor_dimension5 = { 1, { 20 } };
const TfArray<1, float> quant5_scale = { 1, { 0.014930061995983124, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[20*148] = { 
  2, -7, -24, 69, 15, 57, 38, -53, 42, -68, 7, 44, -77, -54, -12, 96, 34, 81, -36, -36, 94, -15, 92, 28, -78, 73, -37, -37, -57, -77, 34, 41, 69, -70, -81, 53, -50, 72, -18, -66, 32, -20, -80, -36, -90, 75, -39, 83, -64, -69, -16, -88, 42, -17, -77, 67, 97, 77, 101, 63, 43, -33, 16, -63, -9, -62, 8, 38, 89, -6, 30, -76, -53, -19, -19, -64, 63, 33, -25, 89, 37, 7, -6, 40, -9, 23, -88, -1, -63, -80, 44, -12, -39, 92, 0, -82, 103, 62, -62, -27, 4, -87, 30, 60, -15, -29, -27, 15, -43, -35, 87, 22, -6, 71, -59, 80, -32, 44, -85, 42, 56, 13, 32, 101, -86, -6, 72, 16, 89, -3, -73, -45, 101, 38, 90, -40, 16, 106, -12, 15, 57, 8, -54, -50, -26, -9, -11, 58, 
  -96, 8, 90, 42, 9, -12, 6, 2, 18, 71, -82, 21, -22, -8, 28, -75, 56, 29, 77, -80, -37, -31, 58, -40, 27, 25, -39, 48, -46, -94, -38, 68, 62, 72, 44, -53, -100, -11, 6, -23, -20, -32, 110, 82, 69, -1, 92, -27, 60, 35, -31, 11, 12, -36, -19, -102, -93, 73, 78, -85, -29, 59, -46, -24, -29, -7, 61, -106, 44, -34, 83, -64, 46, -16, 69, 127, -3, -45, -7, 125, 7, -86, -41, 6, 50, 11, -17, -69, 21, -22, 32, 31, 87, 22, 5, 54, -47, -81, 15, -87, 20, 91, -3, -16, -70, 44, 70, -64, -19, -19, -30, -81, 108, 46, -54, 15, -1, 4, -88, -82, 5, -113, -55, -68, 29, -24, -20, 17, -99, 71, -54, -50, 40, -51, 69, 38, -83, -52, -36, 40, -113, -6, -29, -62, -15, 42, 41, 28, 
  63, -13, -84, -69, 42, -51, 60, 82, 93, -8, -74, 16, -71, 47, -57, 68, 32, 57, 1, 41, 97, -91, 54, -77, 12, -25, 93, 48, -50, -76, -49, 64, 50, -70, -19, -32, -84, -6, 56, -74, 50, 50, -91, -16, 35, -18, -51, -78, 35, -25, 50, -22, -17, -2, 51, -80, 10, 13, 11, -27, 89, -34, -15, 16, -27, 57, 20, -55, -30, -33, -5, -95, 7, 82, -17, -84, -83, 53, -48, -59, 40, -53, 35, -3, 8, 16, -24, -2, -77, 0, -69, 81, 22, -34, 97, 66, 31, 49, 34, 28, -94, -84, -50, -69, 44, -38, 86, 69, 9, -17, -46, 51, 7, -78, -61, -81, 46, 99, -22, 42, -50, 79, 98, -94, 86, 82, 26, 64, -82, -5, 55, -59, 18, 48, 49, 47, -48, 72, 58, 34, -14, 85, 89, 88, -79, 2, -81, 9, 
  -74, 46, -46, 65, 0, 50, -17, 87, 41, -90, 72, 71, 40, 53, 35, -29, -82, -55, 25, 54, -71, 33, -70, -44, 52, 42, -77, 51, 74, 56, -51, 33, 74, -50, 52, 5, 88, -87, 24, 64, -73, 66, 8, 82, 100, -68, 3, -55, 66, 45, -70, -10, -26, -105, 16, -82, -91, -103, -47, -19, 81, 26, 85, 63, -72, -95, 48, -91, -69, -96, 49, -58, -60, -77, 29, 41, -28, 105, 42, 88, 12, 56, 60, -37, -25, -86, -16, -45, 52, -46, 32, 26, -87, 5, 73, -45, -65, -27, 69, -31, -39, -16, 71, -64, -54, -13, 5, -34, 10, 20, -89, 22, 4, 65, 13, 94, -95, -3, 61, -13, -98, 71, -3, 24, -89, -3, -8, -66, 17, 24, -44, -95, -33, 78, -26, -55, -72, 14, 1, 59, 52, 57, 17, -45, 10, 15, -48, -74, 
  83, 18, 19, -56, -71, -78, 77, -28, -50, 53, -33, 14, -66, -48, -72, 48, 52, 60, -13, -27, -15, 86, -24, -20, -35, 0, 66, 62, -94, -82, 40, -67, 82, -74, -36, -52, -35, -87, 21, 54, 13, 32, -82, -32, 58, -57, 75, 62, -16, 60, 56, 66, -81, -30, -32, 89, 57, 70, 80, 52, -89, -83, 84, 85, 0, 50, -47, 92, -101, -28, -89, 21, 63, 29, 47, 49, -38, -23, -43, -39, 70, -96, 46, -72, 29, -59, 18, -73, 62, -38, -39, 1, 21, 60, 25, 0, 15, -24, -75, -79, -24, -89, 19, -32, 85, -54, -96, -27, -69, 28, -66, -2, -54, -6, 38, -9, -42, -71, -57, -16, 83, -31, -61, -16, -87, 2, 87, -80, -49, 36, -35, -21, 35, -22, -27, -27, 46, 46, -94, 65, 26, 11, 58, 6, 61, -98, 71, 13, 
  -34, 77, 13, -9, -37, -73, 14, 102, -33, 26, -87, -31, -92, 50, 22, 3, -84, 32, -26, 13, -71, -76, -5, -44, 76, -21, 31, -9, -42, 101, -14, -5, 80, -55, 27, -86, 71, -61, 35, 90, 62, 33, -72, -31, 12, -100, -77, -70, -8, 65, 91, -10, 37, -35, 48, 63, 37, -8, 59, 12, 30, -89, 69, -72, -22, 4, -31, 82, 89, 48, 95, -40, 71, -67, -102, -67, -7, -20, 58, 5, -71, 41, -44, 82, -4, -70, 33, -2, 101, -13, 16, 11, -55, 80, 9, -4, -7, 36, 3, 64, -9, 34, 83, -52, 26, 21, 100, -60, 38, 58, -6, -13, 24, 61, 64, 14, 52, -71, 31, -56, -92, 59, -71, 19, 8, 95, -11, -32, -43, -84, 12, 37, -57, -29, 24, 90, 48, -71, 80, 95, 58, 2, 5, -50, 19, -50, 91, 94, 
  44, -31, -31, -47, -54, -101, -37, 64, -40, 3, -9, -12, -4, 52, 33, -21, -45, -55, 91, 70, -52, 13, -49, 58, -44, -15, 93, -86, 74, 20, 60, -96, -4, -17, -81, 52, -94, 36, -77, 100, -6, 26, -4, 8, -47, -84, 93, -55, -13, -25, -69, 77, -89, 55, 27, -15, 4, 76, 49, -40, -66, 5, 65, -64, 42, 21, -93, 57, -77, -58, 11, 82, -34, 40, 25, 65, 42, 82, 48, -47, 69, 55, 0, 24, -61, -33, 56, 20, -50, -47, -75, 56, -44, 85, -36, -99, -51, -64, -92, -14, -63, -61, 0, -32, 89, -20, -18, -71, -57, -9, -9, 53, 70, -101, 28, -19, 49, -44, -88, -39, -57, 15, -86, -5, -42, -84, -14, 37, -32, -87, 36, -97, -14, 41, 60, 72, -85, 38, 63, 92, 32, 52, -44, -103, -77, 5, 63, -92, 
  75, -102, 35, 91, 91, 20, 18, 31, -40, 73, -30, 85, -43, 30, -72, -103, -41, -61, -75, 82, 72, -72, -61, -11, -31, 85, -36, 18, -101, -23, 13, 81, 12, -94, -44, -100, -26, 30, 75, -36, -9, 36, 106, 102, 41, -3, 26, -77, -53, 51, -64, -25, -18, 15, -33, -64, -87, 65, 61, -100, -70, -36, 45, -75, 47, 22, 18, -45, -51, 93, -64, 11, -24, 34, 1, 25, -38, 64, -43, 40, 88, -106, 49, -13, 16, -102, 32, 34, 56, -43, -34, -93, 4, -64, -89, -51, -42, -93, -5, 81, -40, 48, -13, -95, -22, -43, -53, -94, 82, -44, -65, -73, 24, 36, 91, -32, 65, -25, -46, 29, -40, 17, -19, -90, 28, 28, -75, -90, -27, -25, 48, -15, -30, 7, -74, 50, -28, -31, -2, -18, -22, 48, 48, 70, 27, 52, -13, -81, 
  50, 89, 55, -22, -93, 56, -16, -62, -12, -20, 2, 56, 53, -40, 12, -46, 36, -50, 92, 16, 86, 62, 83, 36, 56, 58, 66, -13, 77, -89, 50, -97, -18, -5, -84, -32, -90, 78, -69, 13, -54, -55, -93, -42, -90, 25, -39, -17, -55, 25, -95, -100, 93, -66, 46, 42, 9, 42, -14, -41, 58, -27, 78, -43, 1, -97, 80, 66, 56, -54, -46, -34, 12, -83, -35, -85, -68, -49, -59, 79, -53, -60, -80, -49, 78, 17, -9, 31, 52, 49, -4, -93, -92, -26, 70, -11, 85, 20, 40, -58, -72, -63, -48, 40, 7, 66, -28, 7, 21, -13, -47, 60, 21, 47, 72, 86, 37, -57, 86, -20, 72, 83, 9, -25, 56, -86, 22, 100, -83, 79, -84, 81, -94, -23, -64, 2, -66, 91, 29, 87, 87, -1, 71, -49, -75, 17, 45, -63, 
  -80, 46, -81, -10, -60, 61, -87, 2, -51, -96, -81, -65, -96, -23, -60, 79, -8, 60, 72, -60, -18, 64, 22, 94, 101, 69, 8, 31, 0, 47, -41, -25, -69, -1, 71, 32, 69, 76, -12, 14, 19, 38, -52, 25, -40, -96, 65, 42, 86, -74, 53, 95, -92, -90, -56, 20, 57, 13, -87, 32, -85, -52, -66, 76, 3, -21, -90, -26, -65, 43, -59, 67, 87, 4, -15, -74, 88, -32, -103, 70, 52, 97, -81, -53, -67, 77, -65, -50, 49, 20, 80, 40, -25, -10, 14, 92, 0, -89, -73, -41, 63, -73, -82, -33, 16, -2, -96, -42, 42, 38, 49, -52, -44, -41, 80, 61, 80, 57, 68, 51, 80, -93, -44, 87, -51, 47, 73, -29, -45, 42, -42, -53, -33, -24, -80, 48, 89, 1, 19, -93, 81, -61, 40, -1, 14, 39, 93, -5, 
  90, 26, 40, -98, -82, -35, 61, 20, -2, 36, -70, 33, 30, -72, 51, -53, 2, 3, 39, 25, -79, 50, -86, 80, 85, -14, -43, -27, 74, 70, -90, -74, -73, -17, 102, 90, -24, -80, -80, 30, 33, -16, 1, -34, -36, 64, 3, -97, 53, 41, -27, -57, -15, -2, 74, 90, -60, -38, 26, -12, 29, 37, 67, 70, 28, -91, -84, 47, 48, 31, 80, 15, -18, -36, -6, 83, 32, -66, 40, 100, -38, -64, 33, -62, -39, 69, -31, 29, -34, -46, 2, 95, 49, -48, -11, 9, -51, 38, -84, 50, 86, 64, 49, 44, 51, -42, 6, -84, 78, 11, -20, -1, 29, 50, -98, 10, -25, 87, -32, -53, -44, -78, -55, -70, 85, 50, -68, 25, 49, -84, 67, -37, -71, -88, 34, 33, -8, -85, 93, 62, -36, -68, -41, 30, -13, -90, -6, -32, 
  -20, 25, 81, -39, -96, -92, 93, -43, 68, -27, 80, 85, 58, 84, -41, 39, -45, -38, 86, 0, -24, -23, 92, 2, 28, 37, 60, 45, 97, 36, -10, -22, 2, -42, 24, -24, -70, 16, 19, 55, 36, 65, 76, -24, -60, -39, 13, 37, -93, -17, -81, 58, 21, 25, 82, 48, 41, -26, 3, -87, 67, 44, -11, -35, 61, 51, 56, -32, -28, -30, -83, -5, -63, -66, 71, 24, 47, 72, 36, 11, 40, 85, -85, -55, -93, -88, -64, 45, -13, 63, 49, -77, -95, -74, 18, 29, 44, 66, -15, -25, -12, -6, 74, 70, 62, 38, 10, 96, 1, -82, -19, 12, 45, 34, -97, -72, -85, 14, 67, 41, 104, 95, 14, -13, 0, -19, -45, -66, 106, 80, -52, 65, 47, -13, -78, 28, -65, 81, -40, 63, 1, 21, -7, 49, 71, -82, 10, -32, 
  -45, -94, 1, -31, 59, -85, -58, -95, -79, 47, -23, -91, 24, 52, -34, 72, 12, -33, 81, -27, 46, 55, -61, 61, 49, -31, 7, -47, 82, -26, -42, 23, -95, 88, 60, 61, 79, -65, -83, -61, -12, 15, -79, -48, -98, -39, 90, 55, -15, 97, 65, -87, -98, 18, -64, -96, -66, 30, -19, 43, -32, -71, -75, 65, 16, 24, 65, 37, 8, 67, 0, -46, 44, 63, 27, -97, -39, 74, -85, -85, 15, 42, 83, 63, 91, 74, -90, -57, 4, 60, -70, 88, 20, 16, -68, -89, 35, 10, 63, -22, -67, 57, 47, 31, -3, -82, -7, 78, 49, 15, -5, -33, 3, -48, -66, 15, -47, -32, 87, 51, 55, -10, 34, -53, 32, 39, -98, 53, -54, 83, -6, 52, 79, -7, 30, 90, 52, -5, 76, 98, 61, 20, 78, -25, -38, -28, -96, 68, 
  18, -98, -56, -8, 83, 97, -81, 93, -12, 25, 20, 27, 88, 28, -17, -68, -97, -14, -78, -35, -74, -76, -4, -30, -40, -97, -65, 86, -15, 9, 31, -93, -71, -93, -12, 25, 46, -9, 81, -27, 90, 47, 80, -72, 81, -49, -5, 54, 99, 65, 36, 49, -69, -44, 92, -36, 19, 70, 52, -15, 3, -31, -14, -73, 66, 78, 82, 80, 21, 95, -79, -16, 64, -16, 41, -72, -47, -47, 43, -58, -40, 43, -29, -33, 53, 16, 71, 84, -5, -96, 7, 21, -66, 53, -93, -70, -43, 92, 1, -49, 18, 86, 24, -72, -59, 42, 1, -9, -27, 42, 63, -90, -61, 29, -64, 54, 55, -54, 57, -84, -2, -35, -43, -31, 89, 19, -77, 77, 37, 84, -79, -75, 28, -2, -80, -88, 44, -35, -44, 81, 84, -13, 55, -94, -27, 68, 45, -51, 
  91, -79, -58, 12, 0, -53, -38, 39, 52, 38, 100, -92, -79, 100, -91, -33, -81, 18, 61, -72, 88, 101, -44, 77, -86, -52, -9, -75, 82, -22, 104, -48, -39, 66, -10, -59, -72, 24, 71, -89, -104, 73, -102, 55, -24, 53, -42, -65, -95, -40, -17, 46, 35, -14, -70, -60, 92, -20, 88, -52, 10, 45, -55, 93, 18, 92, 88, 65, -13, 56, 14, -56, 93, -36, 87, 40, -38, 18, -9, 13, 57, 16, -61, -40, 24, -72, 80, 14, -75, 25, -39, 36, -9, 61, -78, 3, 82, 82, 85, 105, -85, 96, -58, 78, -75, -29, 66, -81, -33, -52, -38, -10, 88, 57, -97, 52, 102, -77, 80, 87, -44, -7, -5, -52, -62, -71, 0, 99, 95, -59, -27, -53, 2, 3, 72, 57, 96, 51, -76, 85, -26, 43, -25, -43, 74, 72, 42, -54, 
  0, 83, -73, -92, -92, 27, -12, 16, 36, 32, -6, 38, -55, 46, 46, 76, 16, 43, 34, 58, -90, 82, -80, 43, 22, 1, -44, -36, -19, -54, 26, -34, -35, 51, -7, 21, 0, -91, 25, 87, 56, -47, 29, -70, 69, -60, -88, -25, -71, 67, 41, -8, 69, 83, 39, -56, 85, 43, -71, 82, 2, -61, 18, -42, 16, 40, 15, -58, 9, 63, -84, 80, 79, 85, 40, 70, -41, 22, 83, 36, -69, -58, 13, 92, 98, 75, 9, 51, 56, 98, -3, 97, 20, 62, 94, 69, -81, 48, 52, 45, 74, 85, 93, -30, 66, -62, 15, 39, 97, -56, 29, -83, -96, 17, 57, -62, -33, -86, -3, -11, -52, 19, -13, -35, 36, -23, -57, -46, -28, -73, -18, -29, 20, 83, -65, -40, -53, -29, 12, 14, -52, 29, -41, -7, 80, 16, 93, 11, 
  1, -63, -39, -7, 79, -23, -33, -71, 36, -86, -86, -31, 23, 48, -34, 36, -77, -49, 43, -32, -82, -57, 37, -42, 41, -32, -17, 75, -69, 71, 35, -1, 76, -59, -29, -52, 29, -84, -44, 3, 0, -17, 17, 71, -11, -79, 76, -90, -7, -39, 8, -12, -18, -72, -14, -93, -14, -20, 63, -69, -63, 84, -57, 6, -69, 45, 2, -37, -2, 93, -81, -20, -51, 84, 73, 51, -46, 26, -59, 19, 21, 87, -98, -32, -6, 66, 5, -60, 92, -24, 12, 95, 91, 16, 15, -47, 9, -30, 86, -46, -14, -13, -17, -14, 86, 70, 46, 92, -17, -57, 55, 24, 68, -91, -89, 33, -28, 87, -56, -83, 48, -14, -60, -11, 92, 19, -10, -87, 88, 87, -18, 79, -15, 22, -68, 2, 65, -69, 92, -88, 81, -24, 56, -40, -51, 32, 92, 60, 
  -22, 52, 83, 65, 67, -26, -34, 86, 38, -9, -31, 99, -31, 74, -66, -29, -65, 29, 94, -50, 56, -38, -69, 100, -49, -72, -46, 35, -3, -53, -9, -70, 7, 28, 13, 100, 97, -56, 65, -84, -97, -32, 95, -34, 26, -68, 5, 90, -77, 44, -48, -59, 88, 49, 27, -75, 72, -85, -22, -47, 33, -76, 49, 96, -19, 55, -7, 4, 36, -23, 77, -32, 67, 91, 42, 20, -75, -77, 68, -72, -75, -86, -83, 21, 55, 95, -34, 26, 26, 47, 2, 98, -87, -46, 74, 55, 45, -31, 92, -86, 89, 43, 11, -56, -52, -95, -75, 96, 30, -93, -85, -49, 73, 7, -70, 26, 71, 100, -45, -10, -55, 93, 29, 90, 6, 45, 49, 87, 96, 89, 54, 46, -56, 80, 11, -16, 96, 62, 25, -17, -94, -86, -87, 72, 54, 2, 32, 45, 
  -88, -20, 47, -101, 42, 14, -59, -4, 2, -29, -85, -32, -79, -64, -68, -46, 11, -53, -48, 43, -44, 87, -48, 82, -37, -80, 1, -23, -82, -63, 51, -37, -57, -83, 102, 83, 32, -71, -80, -30, -77, 15, -64, 45, -3, -21, 93, 17, -83, -87, 11, -78, 49, -51, 67, -64, -59, -56, -22, 76, -26, -46, -59, 82, 54, -46, 91, -74, 10, 92, 66, 59, 79, -39, -98, 24, 91, 12, -34, 39, 33, 46, 90, 2, 52, 23, 88, 15, 0, -73, -88, 83, 67, -26, -65, -66, 59, 27, 98, -55, -93, 102, 28, 15, -44, 8, -45, -65, 10, 60, -62, 6, -102, -47, -60, -79, 49, 45, -80, -82, 90, -49, -21, 23, 33, 99, -16, -35, 11, 13, -81, -39, 9, 0, -9, -48, 31, 100, -36, 35, 74, -25, -9, -35, 87, 78, 30, 37, 
  -14, 56, -13, -71, -83, -46, 15, -26, 57, 53, -92, 65, 55, -13, -15, -53, -15, -95, -64, 15, -49, -101, 65, -89, -19, -10, -76, -53, 24, 67, -80, 3, 72, -73, -3, 22, -102, 6, -5, 3, -79, -83, 11, 40, -14, -94, -107, 11, -24, -12, 11, 31, -98, 19, 31, -66, 38, -96, -80, 66, -91, 51, -87, 20, -88, -26, -30, -81, -86, -72, -108, 50, -44, -28, -34, 12, -80, -111, -100, -56, 61, -20, -16, -95, -31, 24, 73, -23, 16, -13, -101, 6, -77, -32, 16, -93, -76, -78, 89, -71, -40, 63, 57, -84, -26, 53, -103, -78, -17, 50, 92, 60, -70, -65, 29, -1, 12, -43, -26, 12, 113, 33, 58, -33, 45, 80, -72, 17, -34, 17, -54, 19, 96, 71, 28, 112, 62, 93, -35, -24, 54, -47, 50, 43, 17, 92, -53, 91, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 20,148 } };
const TfArray<1, float> quant6_scale = { 1, { 0.0019133760361000896, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const TfArray<2, int> tensor_dimension7 = { 2, { 1,20 } };
const TfArray<1, float> quant7_scale = { 1, { 1.1367508172988892, } };
const TfArray<1, int> quant7_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&quant7_zero, 0 };
const TfArray<2, int> tensor_dimension8 = { 2, { 1,10 } };
const TfArray<1, float> quant8_scale = { 1, { 0.2930731475353241, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,2 } };
const TfArray<1, float> quant9_scale = { 1, { 0.2228805273771286, } };
const TfArray<1, int> quant9_zero = { 1, { 10 } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&quant9_zero, 0 };
const TfArray<1, float> quant10_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,6,5 } };
const TfArray<1, int> outputs0 = { 1, { 7 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 7,4,3 } };
const TfArray<1, int> outputs1 = { 1, { 8 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 8,2,1 } };
const TfArray<1, int> outputs2 = { 1, { 9 } };
const TfLiteSoftmaxParams opdata3 = { 1 };
const TfArray<1, int> inputs3 = { 1, { 9 } };
const TfArray<1, int> outputs3 = { 1, { 10 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension0, 148, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 8, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 2960, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 160), (TfLiteIntArray*)&g0::tensor_dimension7, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension8, 10, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension9, 2, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension9, 2, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 11, };
const size_t tflNodes_subgraph_index[] = {0, 4, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  10, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_790160_4_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 11;
  for (size_t i = 0; i < 11; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_790160_4_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_790160_4_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_790160_4_invoke() {
  for (size_t i = 0; i < 4; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_790160_4_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
