name=Stress_inferencing
version=1.0.5
author=EdgeImpulse Inc. / Rafael Lima
maintainer=Rafael Lima
sentence=Arduino library for running Edge Impulse stress detection model
paragraph=This library contains the signal processing code and trained machine learning model for stress classification (normal vs stress). Includes integration for ESP32 and compatible boards.
category=Data processing
url=https://edgeimpulse.com
architectures=*
depends=Arduino_LSM9DS1, PDM, Arduino_OV767X
includes=Stress_inferencing.h, ei_run_classifier_stress.h
